name: CI

on:
  push:
    branches:
      - master  # Change to your default branch if necessary
  pull_request:
    branches:
      - master  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Change to your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest Main_project_folder/test_calculator.py  # Adjust the path as necessary
